experiment_name: "SAXS_NEW_VAE"
run_name: saxs_cylinder_ag_newvae
mlflow_uri: https://mlflowts.irit.fr/
dataset:
  conversion_dict:
  hdf5_file: /projects/pnria/caroline/AUTOFILL/data_sept_25/cylinder_saxs_library_no_noise_meta_diameter_metric.h5
  metadata_filters:
  requested_metadata:
  sample_frac: 1.0
transforms_data:
  y:
    PreprocessingSAXS:
      pad_size: 1000
  q:
    PreprocessingQ:
      pad_size: 1000

training:
  array_train_indices: /projects/pnria/caroline/AUTOFILL/data_sept_25/train_(pair_saxs_les).npy
  array_val_indices: /projects/pnria/caroline/AUTOFILL/data_sept_25/val_(pair_saxs_les).npy
  weighted_loss : True
  weighted_loss_limit_index: 300
  T_max: 100
  batch_size: 8
  beta: 1.0e-05
  eta_min: 1.0e-10
  max_lr: 1.0e-04
  num_epochs: 300
  num_gpus: 1
  num_nodes: 1
  num_workers: 1
  patience: 40
  use_loglog: true
  min_delta: 0.00001

model:
  type: vae
  vae_class: ResVAE
  args:
    in_channels: 1
    output_channels: 1
    input_dim: 1000

param_grid:
  model.args.latent_dim: [ 128, 64 ]    
  training.beta: [ 1.0e-03, 1.0e-04, 1.0e-05, 1.0e-06 ]    