experiment_name: "AUTOFILL_LES_1000_gridsearch"
run_name: les_cylinder
mlflow_uri: https://mlflowts.irit.fr/
dataset:
  conversion_dict: /projects/pnria/caroline/AUTOFILL/new_data/LES/conv_les.json
  hdf5_file: /projects/pnria/caroline/AUTOFILL/new_data/LES/data_les.h5
  metadata_filters:
    material:
    - Ag
    shape:
    - Cylindre
    technique:
    - LES
    type:
    - simulation
  requested_metadata:
  - shape
  - material
  sample_frac: 1.0
transforms_data:
  y:
    PreprocessingLES:
      pad_size: 1000
  q:
    PreprocessingQ:
      pad_size: 1000

training:
  T_max: 100
  batch_size: 16
  beta: 1.0e-05
  eta_min: 1.0e-08
  max_lr: 1.0e-04
  num_epochs: 300
  num_gpus: 1
  num_nodes: 1
  num_workers: 1
  patience: 40
  use_loglog: false
  min_delta: 0.00001

model:
  vae_class: ResVAEBN
  args:
    in_channels: 1
    output_channels: 1
    dilation: 1
    input_dim: 1000
    latent_dim: 128
    down_channels: [8, 16, 32, 64, 128, 256, 512]
    up_channels: [ 512, 256, 128, 64, 32, 16, 8]
    strat: "y"

param_grid:
  model.args.latent_dim: [ 128, 64 ]    
  training.beta: [ 1.0e-03, 1.0e-04, 1.0e-05 ]    